name: Build & Deploy
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build multi platform
      uses: dawidd6/action-docker-publish-changed@master
      with:
        docker_username: ${{ secrets.DOCKER_USERNAME }}
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        github_token: ${{secrets.GITHUB_TOKEN}}
        platforms: linux/amd64,linux/arm64,linux/arm
        tag: latest
